### ISSUE TITLE
[Task] Step 1. DataBase 구축하기

### ISSUE THREAD

**Issue by kyungjaecheong** [kyungjaecheong/Kor-DEEPression#1]
## Task Card

**Assignee** : KyungJaeCheong

#### Job Description
> 작업 내용

- [x] 국민건강영양조사 2014, 2016, 2018, 2020 SPSS 원본 데이터 다운로드
- [x] 클라우드 데이터베이스 생성 (ElephantSQL : 무료 요금제)
- [x] 변수 선정 및 RDB로 넣을 수 있는 형태로 가공하기
- [x] postgresql로 RDB 생성 및 변수 insert
