### ISSUE TITLE
[Task] Step2-1. Data Query

### ISSUE THREAD

**Issue by kyungjaecheong** [kyungjaecheong/Kor-DEEPression#16]
## Task Card

**Assignee** : KyungJaeCheong

#### Job Description
> 작업 내용

- [x] Cloud DB에서 SQL 쿼리를 통해 데이터 가져오기
- [x] EDA용 csv data 생성
- [x] Modeling용 csv data 생성
- [x] 코드 구조 수정
