### ISSUE TITLE
[Task] Step 2-3. Standardization & Encoding

### ISSUE THREAD

**Issue by kyungjaecheong** [kyungjaecheong/Kor-DEEPression#18]
## Task Card

**Assignee** : KyungJaeCheong

#### Job Description
> 작업 내용

- [x] Min-Max-Scaling 실시
- [x] One-Hot-Encoding 실시
- [x] 학습 및 테스트에 이용할 데이터 생성
