### ISSUE TITLE
[Task] Step 3-2. Web page Deployment

### ISSUE THREAD

**Issue by kyungjaecheong** [kyungjaecheong/Kor-DEEPression#29]
## Task Card

**Assignee** : KyungJaeCheong

#### Job Description
> 작업 내용

- [x] Prediction page 완성 및 테스트
- [x] Result page 완성 및 테스트
- [x] Dashboard page 완성 및 테스트
- [x] Home page 및 Info page 최종 수정
- [x] Koyeb Deployment Test
