### ISSUE TITLE
[Task] 3-4. Final Report

### ISSUE THREAD

**Issue by kyungjaecheong** [kyungjaecheong/Kor-DEEPression#31]
## Task Card

**Assignee** : KyungJaeCheong

#### Job Description
> 작업 내용

- [x] 최종 보고서 작성
- [x] 발표 ppt 및 발표 script 작성
- [x] 발표 영상 녹화
- [x] 최종 보고서 및 영상 제출
- [x] 블로그 포스팅 작성
