### ISSUE TITLE
[Task] 2-6. Step 2-6. Convert to .tflite file

### ISSUE THREAD

**Issue by kyungjaecheong** [kyungjaecheong/Kor-DEEPression#45]
## Task Card

**Assignee** : KyungJaeCheong

#### Job Description
> 작업 내용

- [x] Final model들의 h5 파일을 directory형태로 저장
- [x] tf.lite로 .tflite 파일 생성
- [x] .tflite 예측 기능 테스트
